# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: touch .env
            - run: echo PORT=${{ secrets.PORT }} >> .env
            - run: echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env
            - run: echo DOMAIN=${{ secrets.DOMAIN }} >> .env
            - run: echo SESION_SECRET=${{ secrets.SESION_SECRET }} >> .env
            - run: echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
            - run: echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
            - run: echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
            - run: echo REDIRECT_URI=${{ secrets.REDIRECT_URI }} >> .env
            - run: echo REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }} >> .env
            - run: echo FOLDER_IMAGE_PETS=${{ secrets.FOLDER_IMAGE_PETS }} >> .env
            - run: echo FOLDER_IMAGE_PRODUCTS=${{ secrets.FOLDER_IMAGE_PRODUCTS }} >> .env
            - run: echo FOLDER_IMAGE_USERS=${{ secrets.FOLDER_IMAGE_USERS }} >> .env
            - run: echo ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} >> .env
            - run: echo REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }} >> .env
            # - run: npm i
            - run: pm2 restart petpals
